import json
import os
from typing import Any, Dict, List


class Loader:
    """Writes transformed data to JSON or SQL dump files. No destructive DB ops."""

    def __init__(self, transformed: Dict[str, Any], config: Dict[str, Any], out_dir: str):
        self.tables: Dict[str, List[Dict]] = transformed.get("tables", {})
        self.config = config
        self.out_dir = out_dir

    # ------------------------------------------------------------------
    def run(self) -> Dict[str, Any]:
        fmt = self.config.get("output_format", "json")
        respect_fk = self.config.get("respect_fk_order", True)
        errors: List[str] = []
        output_files: List[str] = []
        rows_written: Dict[str, int] = {}

        table_order = list(self.tables.keys())
        if respect_fk:
            table_order = self._fk_sort(table_order)

        if fmt == "json":
            for table in table_order:
                rows = self.tables[table]
                fname = f"{table}.json"
                path = os.path.join(self.out_dir, fname)
                try:
                    with open(path, "w", encoding="utf-8") as f:
                        json.dump(rows, f, indent=2, default=str)
                    output_files.append(fname)
                    rows_written[table] = len(rows)
                except Exception as e:
                    errors.append(f"{table}: {e}")

            # also write combined
            combined_path = os.path.join(self.out_dir, "all_tables.json")
            combined = {t: self.tables[t] for t in table_order}
            with open(combined_path, "w", encoding="utf-8") as f:
                json.dump(combined, f, indent=2, default=str)
            output_files.append("all_tables.json")

        elif fmt == "sql":
            sql_lines: List[str] = []
            sql_lines.append("-- ETL Studio SQL Dump")
            sql_lines.append("-- Generated by ETL Studio")
            sql_lines.append("BEGIN;")
            sql_lines.append("")

            for table in table_order:
                rows = self.tables[table]
                if not rows:
                    continue
                cols = list(rows[0].keys())
                col_list = ", ".join(f'"{c}"' for c in cols)
                sql_lines.append(f"-- Table: {table}")
                for row in rows:
                    vals = ", ".join(self._sql_val(row.get(c)) for c in cols)
                    sql_lines.append(f'INSERT INTO "{table}" ({col_list}) VALUES ({vals});')
                sql_lines.append("")
                rows_written[table] = len(rows)

            sql_lines.append("COMMIT;")
            fname = "dump.sql"
            path = os.path.join(self.out_dir, fname)
            with open(path, "w", encoding="utf-8") as f:
                f.write("\n".join(sql_lines))
            output_files.append(fname)

        return {
            "ok": len(errors) == 0,
            "output_files": output_files,
            "rows_written": rows_written,
            "staging_used": self.config.get("use_staging", False),
            "transaction_wrapped": fmt == "sql",
            "errors": errors,
        }

    # ------------------------------------------------------------------
    @staticmethod
    def _sql_val(v: Any) -> str:
        if v is None:
            return "NULL"
        if isinstance(v, bool):
            return "TRUE" if v else "FALSE"
        if isinstance(v, (int, float)):
            return str(v)
        escaped = str(v).replace("'", "''")
        return f"'{escaped}'"

    @staticmethod
    def _fk_sort(tables: List[str]) -> List[str]:
        # Simple alphabetical ordering as a proxy; real FK graph would need schema metadata
        return sorted(tables)
